// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: mqqognxbhtlzpypmbbik

class SupabaseConfig {
  static const String supabaseUrl = 'https://mqqognxbhtlzpypmbbik.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xcW9nbnhiaHRsenB5cG1iYmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMjQ2OTAsImV4cCI6MjA3NjkwMDY5MH0.OW05w8Kdezuh8tWrQdKepIiUtwqSD0_2OAgZDntk9po';
}
